packages:
  - 'apps/*'
  - 'packages/*'
  - docs
catalog:
  '@antfu/eslint-config': ^4.12.0
  '@tailwindcss/cli': ^4.1.5
  '@tailwindcss/vite': ^4.1.5
  '@types/lodash-es': ^4.17.12
  '@types/node': ^22.15.3
  '@vitejs/plugin-vue': ^5.2.2
  '@vue/tsconfig': ^0.7.0
  '@vueuse/core': ^13.1.0
  '@vueuse/head': ^2.0.0
  axios: ^1.9.0
  eslint: ^9.24.0
  lodash-es: ^4.17.21
  pinia: ^3.0.2
  sass: ^1.88.0
  tailwindcss: ^4.1.5
  typescript: ~5.7.2
  unplugin-auto-import: ^19.2.0
  unplugin-vue-components: ^28.5.0
  vite: ^6.3.1
  vite-plugin-dts: ^4.5.3
  vite-plugin-pages: ^0.33.0
  vite-plugin-vue-layouts: ^0.11.0
  vitepress: ^1.6.3
  vue: ^3.5.13
  vue-router: ^4.5.1
  vue-tsc: ^2.2.8
